### ISSUE TITLE
Failed to configure list setup in preview page

### ISSUE THREAD

**Issue by cheuklam** [wintercms/winter#1145] opened 2024-06-11 14:19 UTC
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

![image](https://github.com/wintercms/winter/assets/3140097/52a0d9fb-22fe-4cff-ac47-694f117e9362)

relation widget cannot change setup in preview mode. 

### Steps to replicate

1) preview any manage view
2) click on the list setup button on any relation controller widget
3) change order / check / uncheck items
4) Apply

### Workaround

Dont use preview mode, use edit mode

**Comment by LukeTowers** [comment] 2024-07-03 02:57
This is probably caused because the relationcontroller would be in readOnly mode in the preview context, which might be causing the widget to not be bound correctly. @mjauvin is this something you can take a look at?

**Comment by mjauvin** [comment] 2024-07-03 11:52
should we hide the list setup button in preview mode?

**Comment by LukeTowers** [comment] 2024-07-03 16:49
@mjauvin ideally we fix it so that it works correctly, you would still want to use it in preview mode.

**Comment by mjauvin** [comment] 2024-07-03 17:06
@cheuklam I tried to reproduce on a model preview with a relation controller and it's working fine for me. Can you explain how you render the relation controller ?

**Comment by bennothommo** [comment] 2024-10-03 14:25
Closing as there has been no follow up. If the issue persists, please provide further context and we'll be happy to re-investigate.

**Closed as not planned by bennothommo** 2024-10-03 14:25 UTC
