### ISSUE TITLE
Form::submit doesn't include type and value attributes

### ISSUE THREAD

**Issue by ericp-mrel** [wintercms/winter#879] opened 2023-04-02 14:42 UTC
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Form::submit doesn't return the HTML with the correct `type` and `value` attributes, it is missing entirely.

https://wintercms.com/docs/services/html#buttons

<img width="474" alt="Screenshot 2023-04-02 at 9 39 42 AM" src="https://user-images.githubusercontent.com/63664924/229359879-53526e1b-9bf4-432b-ac72-c6dcc3d2f37a.png">

<img width="317" alt="Screenshot 2023-04-02 at 9 39 58 AM" src="https://user-images.githubusercontent.com/63664924/229359884-0b1eb0fb-4560-42ac-8c8a-06713841f9ce.png">

### Steps to replicate

```php
<?= Form::submit('Save', ['class' => 'btn btn-primary']) ?>
```

### Workaround

Pass the missing attribute values into the options parameter as well.

**Comment by ericp-mrel** [comment] 2023-04-02 14:46
This line is preventing the attributes from being set since the `submit()` method is passing null for the name param. https://github.com/wintercms/storm/blob/develop/src/Html/FormBuilder.php#L273

**Comment by mjauvin** [comment] 2023-04-02 16:02
@ericp-mrel can you check if this merged commit has something do to with the bug or not ?

**Comment by mjauvin** [comment] 2023-04-02 16:19
That block you mention causing the issue has been added by this commit:

[2ef32346682c768a9d457c4dba6796f34b644eab](https://github.com/wintercms/storm/commit/2ef32346682c768a9d457c4dba6796f34b644eab)

**Comment by mjauvin** [comment] 2023-04-02 16:44
@bennothommo I assigned you to the issue since you made that change.

**Comment by mjauvin** [comment] 2023-04-02 16:48
duplicate of https://github.com/wintercms/winter/issues/864

**Closed as completed by mjauvin** 2023-04-02 16:48 UTC
Labels: duplicate

**Comment by ericp-mrel** [comment] 2023-04-02 22:31
Sorry, I didn't see the other issue when I searched before creating this issue.
