### ISSUE TITLE
backend/system/updates/install : Winter\Storm\Network\Http::data(): Argument #2 ($value) must be of type ?string, array given

### ISSUE THREAD

**Issue by Quendi6** [wintercms/winter#1050] opened 2024-01-31 11:37 UTC
### Winter CMS Build

1.2

### PHP Version

Other (please specify below)

### Database engine

MySQL/MariaDB

### Issue description

PHP version : 8.3

![image](https://github.com/wintercms/winter/assets/20945117/289610c4-bd32-42a0-ad80-0994fbecb0b0)

We can't install plugins or theme using backend interface.

Full stack trace :

```
TypeError: Winter\Storm\Network\Http::data(): Argument #2 ($value) must be of type ?string, array given, called in /**/public/vendor/winter/storm/src/Network/Http.php on line 469 and defined in /**/public/vendor/winter/storm/src/Network/Http.php:465
Stack trace:
#0 /**/public/vendor/winter/storm/src/Network/Http.php(469): Winter\Storm\Network\Http->data()
#1 /**/public/modules/system/classes/UpdateManager.php(1070): Winter\Storm\Network\Http->data()
#2 /**/public/modules/system/classes/UpdateManager.php(934): System\Classes\UpdateManager->applyHttpAttributes()
#3 /**/public/vendor/winter/storm/src/Network/Http.php(165): System\Classes\UpdateManager->System\Classes\{closure}()
#4 /**/public/vendor/winter/storm/src/Network/Http.php(191): Winter\Storm\Network\Http::make()
#5 /**/public/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Winter\Storm\Network\Http::post()
#6 /**/public/modules/system/classes/UpdateManager.php(933): Illuminate\Support\Facades\Facade::__callStatic()
#7 /**/public/modules/system/classes/UpdateManager.php(737): System\Classes\UpdateManager->requestServerData()
#8 /**/public/modules/system/controllers/Updates.php(963): System\Classes\UpdateManager->requestProductDetails()
#9 /**/public/modules/system/controllers/Updates.php(113): System\Controllers\Updates->getInstalledPlugins()
#10 [internal function]: System\Controllers\Updates->install()
#11 /**/public/modules/backend/classes/Controller.php(416): call_user_func_array()
#12 /**/public/modules/backend/classes/Controller.php(307): Backend\Classes\Controller->execPageAction()
#13 /**/public/modules/backend/classes/BackendController.php(161): Backend\Classes\Controller->run()
#14 /**/public/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Backend\Classes\BackendController->run()
#15 /**/public/modules/backend/classes/BackendController.php(111): Illuminate\Routing\Controller->callAction()
#16 /**/public/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Backend\Classes\BackendController->callAction()
#17 /**/public/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#18 /**/public/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#19 /**/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route->run()
#20 /**/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#21 /**/public/modules/backend/classes/BackendController.php(68): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /**/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): Backend\Classes\BackendController->Backend\Classes\{closure}()
#23 /**/public/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /**/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#25 /**/public/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /**/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#27 /**/public/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /**/public/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#29 /**/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#30 /**/public/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /**/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#32 /**/public/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /**/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#34 /**/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /**/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\Pipeline\Pipeline->then()
#36 /**/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router->runRouteWithinStack()
#37 /**/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router->runRoute()
#38 /**/public/vendor/winter/storm/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute()
#39 /**/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Winter\Storm\Router\CoreRouter->dispatch()
#40 /**/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#41 /**/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 /**/public/vendor/winter/storm/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(25): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#43 /**/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Winter\Storm\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#44 /**/public/vendor/winter/storm/src/Foundation/Http/Middleware/CheckForTrustedProxies.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /**/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Winter\Storm\Foundation\Http\Middleware\CheckForTrustedProxies->handle()
#46 /**/public/vendor/winter/storm/src/Http/Middleware/TrustHosts.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /**/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Winter\Storm\Http\Middleware\TrustHosts->handle()
#48 /**/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /**/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#50 /**/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#51 /**/public/index.php(42): Illuminate\Foundation\Http\Kernel->handle()
#52 {main}
```

### Steps to replicate

Click on an _"+ Install *"_ button in backend setting update page _(backend/system/updates/install)_.

**Comment by mjauvin** [comment] 2024-01-31 12:22
Duplicate of #1034

**Closed as completed by mjauvin** 2024-01-31 12:22 UTC
Labels: duplicate
