### ISSUE TITLE
Error Winter\Storm\Network\Http::data(): Argument #2 ($value) must be of type ?string

### ISSUE THREAD

**Issue by ambyte** [wintercms/winter#1039] opened 2024-01-19 05:47 UTC
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

New installation, when I click to install plugins or install themes occur error

![image](https://github.com/wintercms/winter/assets/454134/734ca3e2-0d0a-4208-a6d4-a11028bc9379)

### Steps to replicate

click to install plugins or install themes

**Comment by m-paniez9292** [comment] 2024-01-19 14:51
Hi all,

I install today a fresh install via web-installer and I have the same problem.

I'm under debian 12 (new installation) and I have this problem with php 8.0 / 8.1 / 8.3.

Thanks

**Comment by mjauvin** [comment] 2024-01-19 16:15
This is a duplicate of #1034 and was fixed in https://github.com/wintercms/storm/pull/163

Please use dev-develop branch until 1.2.5 is released.

**Closed as completed by mjauvin** 2024-01-19 16:15 UTC
Labels: duplicate
