### ISSUE TITLE
Icon Picker throws javascript error

### ISSUE THREAD

**Issue by xitara** [wintercms/winter#862] opened 2023-03-07 21:07 UTC
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

The icon picker throws an error on page loading:

jquery-migrate.min.js?v=1:33 JQMIGRATE: Migrate is installed, version 3.0.1
iconpicker.js?v1:1 Uncaught TypeError: (0 , t.dD) is not a function
    at iconpicker.js?v1:1:699
    at 595 (iconpicker.js?v1:1:739)
    at t (manifest.js?v=1:1:138)
    at iconpicker.js?v1:1:12122
    at t.O (manifest.js?v=1:1:435)
    at iconpicker.js?v1:1:12142
    at e (manifest.js?v=1:1:1368)
    at iconpicker.js?v1:1:112
(anonymous) @ iconpicker.js?v1:1
595 @ iconpicker.js?v1:1
t @ manifest.js?v=1:1
(anonymous) @ iconpicker.js?v1:1
t.O @ manifest.js?v=1:1
(anonymous) @ iconpicker.js?v1:1
e @ manifest.js?v=1:1
(anonymous) @ iconpicker.js?v1:1

### Steps to replicate

Add Icon picker to a model:

icon:
    label: themes.agency::blocks.header.icon.label
    comment: themes.agency::blocks.header.icon.comment
    span: auto
    type: iconpicker
    libraries: ~/modules/backend/formwidgets/iconpicker/meta/libraries.yaml
    
same without `libraries:`

**Comment by damsfx** [comment] 2023-03-07 23:59
Same as #826

**Comment by bennothommo** [comment] 2023-03-08 00:00
@damsfx is correct - duplicate of #826.

**Closed as completed by bennothommo** 2023-03-08 00:00 UTC
Labels: duplicate
