### ISSUE TITLE
Image resizer gets wrong path

### ISSUE THREAD

**Issue by multiwebinc** [wintercms/winter#604] opened 2022-07-14 19:27 UTC
### Winter CMS Build

1.1

### PHP Version

7.4

### Database engine

No database

### Issue description

I'm not sure if I'm doing something wrong or if it's actually a bug, however when I try to resize images using the `ImageResizer` class, the path of `ImageResizer::getUrl()` is incorrect.

### Steps to replicate

I have the following in a component:

```php
$image_path = '/storage/app/media/1U4A2531.jpg';
$resizer = new \System\Classes\ImageResizer($image_path, 300, null);
$resizer->resize();
$thumbnail = $resizer->getUrl();
```

**Expected value of `$thumbnail`:** 

`"/storage/app/resized/64c/80b/aab/1U4A2531_resized_64c80baaba14cb45cedeb7ead22f267bbc16aa20.jpg"`

**Actual value:**

`"/storage/resized/64c/80b/aab/1U4A2531_resized_64c80baaba14cb45cedeb7ead22f267bbc16aa20.jpg"`

### Workaround

This seems very hacky and wrong, but it works if you change [this line](https://github.com/wintercms/winter/blob/e764d0f54f7d259be849224cde4d8c4890aa52f4/modules/system/classes/ImageResizer.php#L526) to:

```
$url = $resizedDisk->url('app/' . $this->getPathToResizedImage());
```

**Comment by LukeTowers** [comment] 2022-07-15 04:32
@multiwebinc can you replicate this with a fresh install of Winter v1.2?
```bash
composer create-project wintercms/winter test1.2 dev-wip/1.2
```

**Comment by multiwebinc** [comment] 2022-07-15 05:37
@LukeTowers It appears to be working correctly with a fresh install of 1.2.

**Comment by LukeTowers** [comment] 2022-07-15 06:13
@multiwebinc I would recommend you check your filesystems.php and cms.php config files against the defaults provided in v1.2 then to verify that they are up to date.

**Comment by LukeTowers** [comment] 2022-07-15 06:13
Will close the issue for now unless it can be reproduced in a fresh install of Winter since it appears to be a configuration problem. Feel free to post your findings once you've resolved it locally!

**Closed as completed by LukeTowers** 2022-07-15 06:13 UTC

**Comment by multiwebinc** [comment] 2022-07-15 06:35
@LukeTowers I'm using 1.1 though, not 1.2. Are the config files from 1.2 compatible with 1.1?

**Edit:**

I was missing `filesystems.disks.local.url`. Adding that fixed the problem. Thanks for pointing me in the right direction.

**Comment by LukeTowers** [comment] 2022-07-15 07:53
No problem, happy to help!
