### ISSUE TITLE
php fatal erorr

### ISSUE THREAD

**Issue by mostafaabdo22** [wintercms/winter#1152] opened 2024-06-25 19:01 UTC
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Winter CMS Forum.*** Detecting Winter CMS build...
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 2113536 bytes)

### Steps to replicate

when i run 
php artisan serve 
or 
php artisan winter:version 
and 
composer update

**Comment by LukeTowers** [comment] 2024-06-25 23:29
I've seen other people report similar issues when they had misconfigurations with their PHP versions, specifically if they have different versions used by the php in the console, composer, or the webserver.

Can you post the specific error you get when running `php artisan serve`? I haven't seen out of memory issues with that command before.

**Comment by mostafaabdo22** [comment] 2024-06-26 16:09
WARN  PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in D:\myproject\vendor\laravel\framework\src\Illuminate\Database\Connection.php on line 760.

   WARN  PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in D:\myproject\vendor\laravel\framework\src\Illuminate\Database\Connection.php on line 760.

This error appears, but I searched. It seems that I must make modifications within the php.ini file, but when I increase the memory value (memory-limit=512M), the error appears again and the values ​​shown in the error increase.

**Comment by LukeTowers** [comment] 2024-06-26 17:11
increasing the memory limit rarely actually solves the problem. It sounds like it's being caused by an infinite loop, possibly by an error being triggered when attempting to connect to the database and then it attempting to connect to the database again to log the error endlessly. Do you have the correct database credentials configured?

**Comment by mostafaabdo22** [comment] 2024-06-26 17:17
Yes, it is correct. I deleted xampp and downloaded it again. It worked, but after a day the error appeared again. I think it has something to do with composer.

**Comment by bennothommo** [comment] 2024-10-03 14:20
We'll close this for now, as there's been no follow up. If the issue persists and you can provide us more info on how to replicate the issue, we'll be happy to re-open.

**Closed as completed by bennothommo** 2024-10-03 14:20 UTC
