### ISSUE TITLE
updates plugin/theme under updates & plugins, got an exception  

### ISSUE THREAD

**Issue by mavrik74** [wintercms/winter#1054] opened 2024-02-12 11:26 UTC
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Winter\Storm\Network\Http::data(): Argument #2 ($value) must be of type ?string, array given, called in /home/mono/web/=================/vendor/winter/storm/src/Network/Http.php on line 469

### Steps to replicate

Go to updates plugin/theme under updates & plugins, got an exception

**Comment by mjauvin** [comment] 2024-02-12 12:17
Duplicate of #1034

**Closed as completed by mjauvin** 2024-02-12 12:17 UTC
Labels: duplicate
