### ISSUE TITLE
Flash timer issue

### ISSUE THREAD

**Issue by wverhoogt** [wintercms/winter#515] opened 2022-03-30 14:56 UTC
### Winter CMS Build

1.1

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Plugins installed

winter.builder, winter.pages, winter.translate, winter.user

### Issue description

When using flash messages in Ajax-requests, you can´t influence de 7 seconds message timer. The handler in FlashListener calls the flash-plugin as follows:
```
ajaxFlashMessages(messages) {
        Object.entries(messages).forEach((entry) => {
            const [cssClass, message] = entry;
            this.snowboard.flash(message, cssClass);
        });
        return false;
    }
```
where` this.snowboard.flash` expects a timing argument as the 4th parameter, and defaults to 7 seconds when not given.

### Steps to replicate

Issue an Ajax-request where the handler flashes a message using the Flash facade like:
```
Snowboard.request(some_element, handlerFunction, { flash: true }
```
No special arguments are needed to observe the result.

**Comment by bennothommo** [comment] 2022-03-31 04:37
@wverhoogt it's not a bug per se - it's simply not providing an API to allow modification of the timer in this scenario.

What I think we'll do is add an event to allow modification of the flash message (and its configuration) on creation.

**Comment by wverhoogt** [comment] 2022-03-31 15:39
AH, ok. For now is´s not too much of a deal.

**Comment by bennothommo** [comment] 2022-04-01 03:58
I've added a `flash.create` and `flash.remove` event to the Flash plugin which you can use to modify the Flash parameters. See: https://github.com/wintercms/winter/commit/192b91af123bc7fdb14045b37534c0027c9ea0e5

You could create a simple Singleton that can set the default duration of Flash messages to another duration:

```js
class FlashDuration extends Snowboard.Singleton {
    listens() {
        return {
            'flash.create': 'onFlashCreate',
        };
    }

    onFlashCreate(flash) {
        flash.duration = 10;
    }
}

Snowboard.addPlugin('flashDuration', FlashDuration);
```

This will be released with the next Winter version.

**Closed as completed** 2022-04-01 03:59 UTC
Labels: accepted
