### ISSUE TITLE
Reordering records does not trigger afterSave() events on model

### ISSUE THREAD

**Issue by hirisov** [wintercms/winter#952] opened 2023-07-25 15:06 UTC
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

If I reorder records using the ReorderController behavior, and define model events like afterSave() or similar in the model, then those never gets executed.
It seem to me https://github.com/wintercms/winter/blob/develop/modules/backend/behaviors/ReorderController.php#L115 never actually saves the moved record.
I think it is logical that if we defined some code for a model event in afterSave(), we want that to run after it's position in the tree changes (eg. in my case I need to do some things if a model is root / not anymore root node).

### Steps to replicate

1, define a model which uses the NestedSet trait
2, add an afterSave() method to it, eg. to log a debug message
3, add a controller with ReorderController nehavior
4, move a node around using the Reorder button in the backend
5, check the log id the afterSave() ever ran

### Workaround

I created a new Behavior in my plugin which extends the \Backend\Behaviors\ReorderController and overriden onReorder() and added 

```
$sourceNode->save();
```

after the 

```
switch (post('position')) {} 
```

part. I also had to copy the `reordercontroller` folder from https://github.com/wintercms/winter/tree/develop/modules/backend/behaviors to my plugin's `behavior` folder.

**Comment by LukeTowers** [comment] 2023-07-26 03:32
The problem is that it actually updates a lot of records through the database when performing a reorder of a nested set, so firing an event on all of them would be a bit overkill. Could you expand on what sort of things need to happen when the node is no longer a root node?

**Comment by hirisov** [comment] 2023-07-26 07:57
Well I have an application specific feature, that certain attributes should only be set for root level nodes, so after a node is moved I have to check if it is root node or not, and if not root have to null its attribute. Also some other attributes are like "inherited" from the root, and when a node's root changes I have to update these attributes based on the new root (for both the moved node and its children).
For us the at least saving all the children is not a problem if that is needed to keep the database consistent with the custom logic we define in beforeSave() etc. 
Moving a node updates the model (changing some of its attributes) so I think in general that should be handled the same way as any other changes regarding the events.
Or imagine if we need to update a calculated field in the model based on it's parents, the afterSave() is a logical place to put such code I think, but that also won't work properly if the reorder doesn't trigger it.

**Comment by bennothommo** [comment] 2023-07-26 13:01
I have had a scenario in the past of needing to update moved items in a nested set - it was to rewrite "locations" / URLs for items, so while I agree with @LukeTowers in that we need to consider performance, there are scenarios where people might need to be able to do a pass on the data after reordering.

One way to do this right now would be to overwrite the `onReorder` method in your controller, calling the behaviour's `onReorder` method first, and then doing whatever you need to afterwards.

```php
     // In your controller
    public function onReorder()
    {
        $this->asExtension('ReorderController')->onReorder();
        
        // your query here to update root nodes
    }
```

**Comment by hirisov** [comment] 2023-07-31 09:43
Thanks for this another workaround, as I understand with this the we need to handle the logic again to collect all the changed nodes (recursively) manually, don't we? I mean if I define something in a model afterSave() and move one node, that might move lot's of others nodes as well (all its children) and most likely I want to run the afterSave() for all of them (as they all changed). I think if we would have a public / protected varibale for this trait (something like `$fireEventsDuringReorder` or similar with a default of `false`) then we could decide on a per model basis if we prefer the current method, or would like to use events (which means more DB queries but makes it work like any other model events).

**Comment by LukeTowers** [comment] 2023-08-01 18:19
Either way you need to write code to collect the changed nodes since reordering for a NestedTree node uses the `performMove()` method which uses the DB itself to reorder the nodes and doesn't actually interact with individual model instances. See https://github.com/wintercms/storm/blob/b9a7c98bf97e0c01485caa6ed2606e5e898f0534/src/Database/Traits/NestedTree.php#L997-L1054

**Comment by bennothommo** [comment] 2023-09-06 07:25
We'll close this for now as I don't think we're going to make any changes to reordering in the short term, and there's workarounds if needed. If you have any further points, let us know and we'll re-open :)

**Closed as not planned by bennothommo** 2023-09-06 07:25 UTC
Labels: needs review
