### ISSUE TITLE
this.theme.id breaks after adding customization to theme.yaml

### ISSUE THREAD

**Issue by alekseyp** [wintercms/winter#1214] opened 2024-09-26 12:49 UTC
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

When adding fields to theme.yaml , theme.id breaks and returns an integer instead of string (sanitized dirName)

Tested on brand-new setup with demo theme.

```
{{ this.theme.id }}
{{ this.theme.dirName }}
```

```
1
demo
```

### Steps to replicate

- Setup demo theme
- Output `{{ this.theme.id }}` anywhere on the page
- See expected string matching folder name
- Modify theme.yaml adding:
```
form:
    fields:
        site_name:
            label: Site name
            comment: The website name as it should appear on the frontend
            default: My Amazing Site!
```
- refresh the page and see an integer instead of the theme folder name

### Workaround

I've switched to `theme.dirName`, since it's public as well.

**Comment by nevmerzhitsky** [comment] 2024-09-26 14:47
The same with the v1.0.471 and SQLite.

**Comment by nevmerzhitsky** [comment] 2024-09-26 14:50
The docs https://docs.octobercms.com/1.x/markup/this-theme.html#properties stays the `id` must be a string including the dir name.

**Comment by nevmerzhitsky** [comment] 2024-09-26 14:51
Meanwhile, the `getId()` returns a proper value https://github.com/octobercms/october/blob/v1.0.471/modules/cms/classes/Theme.php#L106

**Comment by LukeTowers** [comment] 2024-09-26 18:39
@nevmerzhitsky those are October CMS links, not Winter CMS. Is this actually an issue in Winter CMS?

**Comment by alekseyp** [comment] 2024-09-26 20:24
@LukeTowers please see original issue. Which includes all the versions and steps to reproduce

**Comment by bennothommo** [comment] 2024-09-27 02:52
@alekseyp do you have database templates enabled?

**Comment by alekseyp** [comment] 2024-09-27 09:48
@bennothommo I do not. In the test example - I've setup brand new October without any settings or changes and simply modified files.

**Comment by bennothommo** [comment] 2024-09-28 04:04
Brand new October or brand new Winter?

**Comment by bennothommo** [comment] 2024-09-29 08:05
I can confirm however that this behavior does happen as described. Not sure if it's intentional or not though, will need to look into it further.

**Comment by mjauvin** [comment] 2024-09-29 15:44
I did some investigation and what's happening is the `Cms\Classes\Theme::__get()` method actually returns the ThemeData's record id when custom data is set for the theme... so I think this is intentional.

If one wants the actual theme id attribute whether or not theme data is defined, the Theme::getId() method should be used (as the author of this PR did).

**Comment by mjauvin** [comment] 2024-09-29 18:40
Resolved by https://github.com/wintercms/docs/pull/211

**Comment by alekseyp** [comment] 2024-09-30 10:46
> ... so I think this is intentional...

ThemeData record id will be different on each system; depends on the other themes installed, order, etc - it will return different id. 

So what is the point of it as a random integer?

Just trying to understand what is/was the logic...


> Brand new October or brand new Winter?

Sorry for confusion, winter of course. Got confused with all the comments :D

**Comment by bennothommo** [comment] 2024-09-30 11:16
@alekseyp it doesn't appear to be random - it's the ID of the record in the `cms_theme_data` table, which is created when you have customisable data in your theme. It's effectively caused by a race condition due to the rules of Twig's [access logic](https://wintercms.com/docs/v1.2/markup/templating/templating#access-logic-and-priority) that we've implemented in the CMS module - the `getId` method which normally provides the directory is not run because the `ThemeData` model record has an `id` property, which is a higher priority in that logic.

**Comment by LukeTowers** [comment] 2024-10-25 19:17
@bennothommo does https://github.com/wintercms/winter/commit/fb88e6fabde3b3278ce1844e581c87dcf7daee22 fix this issue?

**Comment by mjauvin** [comment] 2024-10-26 00:29
> [@bennothommo](https://github.com/bennothommo) does [fb88e6f](https://github.com/wintercms/winter/commit/fb88e6fabde3b3278ce1844e581c87dcf7daee22) fix this issue?

yes, I have tested this.

**Comment by LukeTowers** [comment] 2024-10-26 09:14
Fixed by https://github.com/wintercms/winter/commit/fb88e6fabde3b3278ce1844e581c87dcf7daee22

**Closed as completed by LukeTowers** 2024-10-26 09:14 UTC
