### ISSUE TITLE
Flysystem disks visibility

### ISSUE THREAD

**Issue by mjauvin** [wintercms/winter#503] opened 2022-03-21 18:41 UTC
### Winter CMS Build

Other (please specify below)

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Issue description

`Laravel\Illuminate\Filesystem\FilesystemManager` now use `Visibility::PRIVATE` by default now when instanciating the LocalAdapter class.

ref. https://github.com/laravel/framework/blob/9.x/src/Illuminate/Filesystem/FilesystemManager.php#L169-L174

So we need to pass `visibility => 'public'` to the Disk config if we want the files/folder created under that disk to be publicly accessible.

The Image Resizer seems to be using the "local" disk in some parts of the code(folders/files creation) and the "system" disk in other parts (for mapping assets resources).

### Steps to replicate

- add this markup to a test page: {{ 'assets/images/my-test-image.jpg' | theme | resize(600,400) }}
- Remove folder `storage/app/resized`
- Open the page URL
- look at the permissions of the `storage/app/resized` folder (and subfolders)

### Workaround

Add `'visibility' => 'public'` to the local disk definition.

**Comment by LukeTowers** [comment] 2022-03-22 20:17
Sounds like instead we should set the permissions property of the system disk config to `cms.defaultMask.folder`

**Comment by mjauvin** [comment] 2022-03-22 20:26
You mean like this, but for the system disk:
```
    protected function registerNativeFilesystem()
    {   
        $this->app->singleton('files', function () {
            $config = $this->app['config'];
            $files = new Filesystem;
            $files->filePermissions = $config->get('cms.defaultMask.file', null);
            $files->folderPermissions = $config->get('cms.defaultMask.folder', null);
            $files->pathSymbols = [
                '~' => base_path(),
                '$' => base_path() . $config->get('cms.pluginsDir', '/plugins'),
                '#' => base_path() . $config->get('cms.themesDir', '/themes'),
            ];
            return $files;
        });
    }
```

**Comment by mjauvin** [comment] 2022-03-22 21:04
Adding this to `Winter\Storm\Filesystem\FilesystemManager` works:
```
    protected function resolve($name, $config = null)
    {   
        if (is_null($config)) {
            $config = $this->getConfig($name);
        }
        if ($name === 'local') {
            $config['visibility'] = 'public';
        }

        return parent::resolve($name, $config);
    }
```

The problem with the `permissions` property of the system disk is that it's more complex:
ref. https://laravel.com/docs/9.x/filesystem#local-files-and-visibility

But we could also just pass the `visibility` parameter to `Storage::put()`:
ref. https://laravel.com/docs/9.x/filesystem#file-visibility

**Comment by mjauvin** [comment] 2022-03-22 21:11
I tried to replace `FileHelper::put($tempPath, $this->getSourceFileContents())` with `FileHelper::put($tempPath, $this->getSourceFileContents(), 'public')` in `modules/system/classesImageResizer.php` and it doesn't work either.

**Comment by LukeTowers** [comment] 2022-03-22 22:16
Hmm, this is odd. The issue is happening on my server but not locally on Homestead. Server creates the directories with permissions 0700 and homestead creates them with 0755. I also tried changing `$disk->put($path, file_get_contents($tempPath), ['visibility' => 'public']);` in the `resize()` method but that didn't have any effect on the server.

Do you have idea what is causing the difference between local and the remote server @mjauvin?

**Comment by mjauvin** [comment] 2022-03-22 22:34
I don't know, could be the PHP user's umask maybe? Not sure.

**Comment by mjauvin** [comment] 2022-05-14 10:51
@bennothommo can you reproduce this as well? Any idea on how to properly fix this?

**Comment by LukeTowers** [comment] 2022-07-08 21:55
Fixed by https://github.com/wintercms/storm/commit/97588cb6051a8fb61d867e20657bdb4d845cc7ea

**Closed as completed by LukeTowers** 2022-07-08 21:55 UTC
Labels: high priority
