### ISSUE TITLE
UI Breadcrumb - styles are broken

### ISSUE THREAD

**Issue by WebVPF** [wintercms/winter#1161] opened 2024-07-12 14:55 UTC
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

## v1.2.6 (current)
![1](https://github.com/user-attachments/assets/c0718438-3c06-46c5-b745-9b944cb64984)

![2](https://github.com/user-attachments/assets/ec6d9145-832e-4c65-b292-f79318fbbc7b)

## v1.2.5
![2024-07-12_085910](https://github.com/user-attachments/assets/15d8bb10-7ce2-412c-8418-59874a17d913)

## Browser Inspector

v1.2.6:
![2024-07-12_090705](https://github.com/user-attachments/assets/7f559da8-18ae-431e-ad3b-c292d0c06ed0)

v1.2.5:
![2024-07-12_090929](https://github.com/user-attachments/assets/1ec08863-63b9-4f57-9d27-347c56427264)

---

Possible reason https://github.com/wintercms/winter/commit/7a460225d17cea0d7dd761d6bb9e4014ec8c73fd

### Steps to replicate

Open the backend page where there are breadcrumbs.

**Comment by LukeTowers** [comment] 2024-07-13 19:27
@WebVPF are you on the latest dev branch? I believe that commit actually fixed the issue caused by an earlier change to how to compile the backend styles.

**Comment by WebVPF** [comment] 2024-07-14 13:31
@LukeTowers Release 1.2.6

I currently have no way to check whether this has been fixed in develop branch.

**Comment by LukeTowers** [comment] 2024-07-15 06:20
@WebVPF can you try applying that commit to your local copy? It's untagged so it's more likely that's the commit that fixed the issue rather than the one that introduced it for you.

**Comment by WebVPF** [comment] 2024-07-15 06:58
@LukeTowers Sorry, I have no way to check.

**Comment by LukeTowers** [comment] 2024-07-16 05:40
Fixed by https://github.com/wintercms/winter/commit/7a460225d17cea0d7dd761d6bb9e4014ec8c73fd, 1.2.7 will be released this week.

**Closed as completed by LukeTowers** 2024-07-16 05:40 UTC
Labels: needs review
